
const fs = require('fs');

const inputPath = '/srv/http/admin/desktop/supabase/migrations/20260224163708_new-migration.sql';
let content = fs.readFileSync(inputPath, 'utf8');

// 1. Basic cleaning (if not already done)
content = content.replace(/ENGINE=InnoDB/g, '');
content = content.replace(/AUTO_INCREMENT=\d+/g, '');
content = content.replace(/DEFAULT CHARSET=[^ ;)]*/g, '');
content = content.replace(/COLLATE=[^ ;)]*/g, '');
content = content.replace(/CHARACTER SET [^ ;)]*/g, '');
content = content.replace(/unsigned/gi, '');
content = content.replace(/int\(\d+\)/g, 'INTEGER');
content = content.replace(/tinyint\(1\)/g, 'BOOLEAN');
content = content.replace(/tinyint\(\d+\)/g, 'SMALLINT');
content = content.replace(/datetime/g, 'TIMESTAMP');
content = content.replace(/current_timestamp\(\)/g, 'CURRENT_TIMESTAMP');
content = content.replace(/`([^`]+)`/g, '$1'); // Remove backticks

// 2. Fix BOOLEAN defaults (0/1 to false/true)
content = content.replace(/BOOLEAN DEFAULT 0/g, 'BOOLEAN DEFAULT FALSE');
content = content.replace(/BOOLEAN DEFAULT 1/g, 'BOOLEAN DEFAULT TRUE');

// 3. Convert ENUM to TEXT
content = content.replace(/enum\([^)]+\)/g, 'TEXT');

// 4. Handle ALTER TABLE ... MODIFY for auto-increment
// MySQL: ALTER TABLE table MODIFY col type NOT NULL AUTO_INCREMENT;
// Postgres: ALTER TABLE table ALTER COLUMN col ADD GENERATED BY DEFAULT AS IDENTITY;
content = content.replace(/ALTER TABLE (\w+)\s+MODIFY (\w+) ([^,;]+) NOT NULL\s+AUTO_INCREMENT( = \d+)?;/g,
    'ALTER TABLE $1 ALTER COLUMN $2 ADD GENERATED BY DEFAULT AS IDENTITY;');

// Cleanup previous failed attempts at SERIAL PRIMARY KEY in MODIFY
content = content.replace(/MODIFY (\w+) SERIAL PRIMARY KEY/g, 'ALTER COLUMN $1 ADD GENERATED BY DEFAULT AS IDENTITY');

// 5. Remove problematic SET commands
content = content.replace(/SET SQL_MODE[^;]*;/g, '');
content = content.replace(/SET time_zone[^;]*;/g, '');
content = content.replace(/SET @OLD[^;]*;/g, '');
content = content.replace(/START TRANSACTION;/g, '');
content = content.replace(/COMMIT;/g, '');

// 6. Fix trailing commas in CREATE TABLE before )
content = content.replace(/,\s*\n\s*\)/g, '\n)');

// 7. Remove any MySQL-style comments that might break things
content = content.replace(/\/\*![^]*?\*\//g, '');

fs.writeFileSync(inputPath, content);
console.log('SQL Migration file refined for PostgreSQL.');
